front:
  build: .
  ports:
    - "8080:8080"
  volumes:
    - ./src:/src
    - /src/node_modules
  links:
    - redis
redis:
  image: redis
  command: redis-server --appendonly yes
  volumes:
    - ./data:/data
mysql:
    image: mysql
